#!/bin/sh

echo "Running pre-commit checks..."

echo
echo "1. Installing dependencies ..."
python3 -m pipenv sync 

echo
echo "2. Checking formatting with black..."
./scripts/check_black.sh
if [ $? -ne 0 ]; then
    echo
    echo -e "\033[1;31mBlack formatting check failed. Please format your code.\033[0m"
    exit 1
fi

echo
echo "3. Checking static code analysis with flake8..."
./scripts/check_flake8.sh
if [ $? -ne 0 ]; then
    echo
    echo -e "\033[1;31mFlake8 linting failed. Please fix the issues.\033[0m"
    exit 1
fi

echo
echo "4. Checking static type checking analysis with mypy..."
./scripts/check_mypy.sh
if [ $? -ne 0 ]; then
    echo
    echo -e "\033[1;31mMypy type checking failed. Please fix the issues.\033[0m"
    exit 1
fi

echo 
echo "5. Checking config fields consistency..."
python3 scripts/check_config_fields.py
if [ $? -ne 0 ]; then
    echo
    echo -e "\033[1;31mConfig fields consistency check failed. Please fix the issues.\033[0m"
    exit 1
fi

echo
echo "6. Running unit tests..."
./scripts/check_tests.sh
if [ $? -ne 0 ]; then
    echo
    echo -e "\033[1;31mUnit tests failed. Please fix the issues.\033[0m"
    exit 1
fi

#TODO unit tests
